# Generated by Django 3.2.18 on 2023-07-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prdct_name', models.CharField(max_length=64)),
                ('prdct_desc', models.CharField(max_length=200)),
                ('prdct_price', models.FloatField()),
                ('prdct_img', models.URLField(max_length=90)),
            ],
        ),
        migrations.DeleteModel(
            name='auction_items',
        ),
    ]
