# Generated by Django 3.2.18 on 2023-07-12 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_auctionitems_prdct_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='AuctionItems',
            name='prdct_owner',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
