# Generated by Django 3.2.18 on 2023-07-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='auctions.AuctionItems'),
        ),
    ]
