# Generated by Django 3.2.18 on 2023-07-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20230718_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitems',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
