# Generated by Django 3.2.18 on 2023-07-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_bids'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitems',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
