# Generated by Django 3.2.18 on 2023-07-23 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auctionitems_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitems',
            name='prdct_desc',
            field=models.CharField(max_length=500),
        ),
    ]
